lastWidthX : 32
lastWidthY : 32
currentWidthX : 64
currentWidthY : 64
OriginX : 100000
OriginY : 192
OriginZ : 100000
Chance_Takaramono_rare : 0.1
Chance_Chest : 0.02
Chance_Monster : 0.08
Takaramono_try_count : 2
Takaramono_generation_count : 5
Maze_Material_Wall : BEDROCK
Maze_Material_ROOF_A : OBSIDIAN
Maze_Material_ROOF_B : GLOWSTONE
Maze_Material_Light : SEA_LANTERN
world : world
