lastWidthX : 48
currentWidthX : 48
OriginX : 100000
OriginY : 192
OriginZ : 100000
Chance_Takaramono_rare : 0.1
Chance_Chest : 0.02
Chance_Monster : 0.1
Takaramono_try_count : 2
Takaramono_generation_count : 5
Maze_Material_Wall : BEDROCK
Maze_Material_ROOF_A : OBSIDIAN
Maze_Material_ROOF_B : GLOWSTONE
Maze_Material_Light : PUMPKIN
ReConstruct_Maze_On_Finish : false
world : world
